// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel():Promise<void>;

export function Decrypt(arg1:string,arg2:string):Promise<string>;

export function Encrypt(arg1:Array<string>,arg2:string):Promise<string>;

export function GetVersion():Promise<string>;

export function ShowErrMsg(arg1:string):Promise<void>;

export function ShowInfoMsg(arg1:string):Promise<void>;
