// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel() {
  return window['go']['backend']['App']['Cancel']();
}

export function Decrypt(arg1, arg2) {
  return window['go']['backend']['App']['Decrypt'](arg1, arg2);
}

export function Encrypt(arg1, arg2) {
  return window['go']['backend']['App']['Encrypt'](arg1, arg2);
}

export function GetVersion() {
  return window['go']['backend']['App']['GetVersion']();
}

export function ShowErrMsg(arg1) {
  return window['go']['backend']['App']['ShowErrMsg'](arg1);
}

export function ShowInfoMsg(arg1) {
  return window['go']['backend']['App']['ShowInfoMsg'](arg1);
}
